import Link from "next/link";
import { ArrowUpRight, BarChart3, BookOpen, FileText, Image, LayoutPanelTop, Package, Settings2, UsersRound } from "lucide-react";
import { requireAdmin } from "@/lib/auth/require-admin";

const modules = [
  { title: "Pages & programmes", description: "About, Our Work, programme stories and SEO copy.", icon: BookOpen, tables: "content_pages · programs", priority: "Build first" },
  { title: "Gallery & media", description: "Uploads, alt text, captions, credits and activity albums.", icon: Image, tables: "media_assets · activity_albums", priority: "Build first" },
  { title: "SHG products", description: "Women-led product listings and enquiry routes—without unapproved prices.", icon: Package, tables: "shg_products", priority: "Build first" },
  { title: "Partner stories", description: "Partner logos, locations, focus areas and source documents.", icon: UsersRound, tables: "partner_profiles", priority: "Build second" },
  { title: "Documents & reports", description: "Legal records, public reports and compliance-library visibility.", icon: FileText, tables: "public_documents", priority: "Build second" },
  { title: "Impact & enquiries", description: "Verified outcome figures, sources and contact-inbox workflow.", icon: BarChart3, tables: "impact_metrics · contact_inquiries", priority: "Build second" },
  { title: "Navigation & settings", description: "Mega menu, footer links, contact details, donation CTA and social links.", icon: Settings2, tables: "navigation_items · site_settings", priority: "Super admin" },
];

export default async function ContentHubPage() {
  const admin = await requireAdmin();
  return <main className="min-h-screen bg-sand-50"><header className="border-b border-line bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 md:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">BSGSS Control Centre</p><h1 className="font-display text-xl font-bold text-ink">Content hub</h1></div><Link href="/admin" className="text-sm font-semibold text-brand-700 hover:underline">← Dashboard</Link></div></header><div className="mx-auto max-w-6xl px-5 py-10 md:px-8"><div className="rounded-2xl border border-brand-200 bg-brand-50 p-7 sm:p-10"><LayoutPanelTop className="h-8 w-8 text-brand-700" /><p className="mt-5 text-sm font-bold uppercase tracking-[.18em] text-brand-700">Publishing foundation</p><h2 className="mt-3 max-w-3xl font-display text-3xl font-bold text-ink">Everything the BSGSS website needs to manage responsibly.</h2><p className="mt-4 max-w-3xl leading-relaxed text-ink-muted">The content data model is ready in the project schema. This hub defines the editorial modules that will connect to create, review and publish screens. Signed in as {admin.displayName || admin.email}.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/admin/admins" className="inline-flex items-center gap-2 rounded-md bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-800">Manage users <ArrowUpRight className="h-4 w-4" /></Link><Link href="/" className="inline-flex items-center gap-2 rounded-md border border-brand-200 bg-white px-4 py-2.5 text-sm font-semibold text-brand-700 hover:bg-sand-50">View public website <ArrowUpRight className="h-4 w-4" /></Link></div></div><section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-brand-700">Management modules</p><h2 className="mt-2 font-display text-3xl font-bold text-ink">Build in this order</h2></div><p className="text-sm text-ink-muted">Schema documented in <code className="rounded bg-white px-1.5 py-1">docs/</code></p></div><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{modules.map(({ title, description, icon: Icon, tables, priority }) => <article key={title} className="rounded-xl border border-line bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><Icon className="h-5 w-5" /></span><span className="rounded-full bg-sand-50 px-2.5 py-1 text-xs font-semibold text-ink-muted">{priority}</span></div><h3 className="mt-5 font-display text-xl font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-muted">{description}</p><p className="mt-5 border-t border-line pt-4 text-xs font-medium text-brand-700">{tables}</p></article>)}</div></section></div></main>;
}
