import Link from "next/link";
import { AdminManager } from "@/components/admin/AdminManager";
import { requireAdmin } from "@/lib/auth/require-admin";
import { db } from "@/lib/db";

type AdminRow = { id: string; email: string; displayName: string | null; role: string; isActive: boolean; lastLoginAt: Date | null; createdAt: Date };

export default async function AdminsPage() {
  const actor = await requireAdmin();
  const { rows } = await db.query<AdminRow>('SELECT id, email, display_name AS "displayName", role, is_active AS "isActive", last_login_at AS "lastLoginAt", created_at AS "createdAt" FROM users ORDER BY created_at ASC');
  return <main className="min-h-screen bg-sand-50"><div className="mx-auto max-w-5xl px-5 py-10 md:px-8"><Link href="/admin" className="text-sm font-semibold text-brand-700 hover:underline">← Control Centre</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-700">Access control</p><h1 className="mt-2 font-display text-3xl font-bold text-ink">Users &amp; roles</h1></div><p className="text-sm text-ink-muted">Your role: {actor.role.replace("_", " ")}</p></div>{actor.role === "super_admin" ? <section className="mt-8"><h2 className="mb-4 font-display text-xl font-bold text-ink">Add user</h2><AdminManager /></section> : <p className="mt-8 rounded-lg border border-line bg-white p-4 text-sm text-ink-muted">Only a super admin can add team members.</p>}<section className="mt-10 overflow-hidden rounded-xl border border-line bg-white"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold text-ink">Current access</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-sand-50 text-xs uppercase tracking-wide text-ink-muted"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Last sign in</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{rows.map((admin) => <tr key={admin.id} className="border-t border-line"><td className="px-5 py-4"><strong className="block text-ink">{admin.displayName || "No name set"}</strong><span className="text-ink-muted">{admin.email}</span></td><td className="px-5 py-4 capitalize text-ink">{admin.role.replace("_", " ")}</td><td className="px-5 py-4 text-ink-muted">{admin.lastLoginAt ? admin.lastLoginAt.toLocaleDateString("en-IN") : "Never"}</td><td className="px-5 py-4"><span className={admin.isActive ? "text-success" : "text-danger"}>{admin.isActive ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table></div></section></div></main>;
}
