import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Download, Handshake } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { PartnersSection } from "@/components/partners/PartnersSection";
import { partners } from "@/components/partners/partners-data";

export const metadata: Metadata = { title: "Our Partners", description: "BSGSS partners in social development through the years." };
const governmentPartners = ["Ministry of Women & Child Development, Govt. of India", "Rashtriya Mahila Kosh, Ministry of Women & Child Development, Govt. of India", "Office of the Development Commissioner (Handicrafts), Ministry of Textiles, Govt. of India", "Ministry of Youth Affairs & Sports, Govt. of India", "National Horticultural Board, Ministry of Agriculture, Govt. of India", "Department of Secondary & Higher Education, EHV Cell, Ministry of HRD", "Municipal Corporation of Delhi, Govt. of NCT of Delhi", "Delhi Social Welfare Advisory Board, Govt. of NCT of Delhi", "Delhi SC/ST/OBC/Minority/Handicapped/Financial Development Corporation, Govt. of NCT of Delhi", "Gender Resource Centre, Department of Social Welfare, Govt. of NCT of Delhi", "The Transport Department, Govt. of NCT of Delhi", "Welfare for Scheduled Caste & Backward Classes, Govt. of Punjab"];
export default function PartnersPage() { return <><PageHeader title="Our partners" lead="Recognising the institutions that have supported BSGSS social-development work through the years." crumbs={[{ name: "About", path: "/about" }, { name: "Our partners", path: "/about/partners" }]} /><PartnersSection /><main className="py-16 sm:py-24"><div className="mx-auto max-w-6xl px-5 md:px-8"><section className="rounded-2xl bg-brand-900 p-7 text-white sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-10"><div><Handshake className="h-7 w-7 text-brand-200" /><h2 className="mt-4 font-display text-2xl font-bold !text-white">Partners in social development</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-brand-100">Select a CSR partner to see the BSGSS programme focus and locations recorded for that relationship. Names are transcribed from BSGSS&apos;s supplied funding-partners document, revised 08 July 2024.</p></div><a href="/documents/bsgss-funding-partners-2024.pdf" target="_blank" rel="noreferrer" className="mt-5 inline-flex shrink-0 items-center gap-2 rounded-md bg-white px-4 py-3 font-semibold text-brand-900 hover:bg-sand-100 sm:mt-0"><Download className="h-4 w-4" />Download the source PDF</a></section><PartnerDirectory /><PartnerList title="Government partners" items={governmentPartners} /></div></main></> }
function PartnerDirectory() { return <section className="mt-14"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-3xl font-bold">CSR partners</h2><p className="mt-2 text-sm text-ink-muted">Every card opens its dedicated partnership profile.</p></div><p className="text-sm font-semibold text-brand-700">{partners.length} partner profiles</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{partners.map((partner) => <Link key={partner.id} href={partner.href} className="group flex min-h-20 items-center justify-between gap-4 rounded-xl border border-line bg-white px-5 py-4 text-sm font-semibold text-ink shadow-sm transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md"><span>{partner.name}</span><ArrowRight className="h-4 w-4 shrink-0 text-brand-700 transition group-hover:translate-x-1" /></Link>)}</div></section> }
function PartnerList({ title, items }: { title: string; items: string[] }) { return <section className="mt-14"><h2 className="font-display text-3xl font-bold">{title}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((partner) => <div key={partner} className="flex min-h-20 items-center rounded-xl border border-line bg-white px-5 py-4 text-sm font-semibold text-ink shadow-sm">{partner}</div>)}</div></section> }
