import type { Metadata } from "next";
import { HandHeart, Mail, ShoppingBag } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";

export const metadata: Metadata = { title: "SHG Products", description: "Handmade products created by women’s self-help groups supported by BSGSS." };

const products = [
  { name: "Handcrafted shawls", description: "A collection of handmade shawls created through women’s self-help groups, bringing warmth, craft and livelihood together.", image: "/images/bsgss/shg-products/shawl.png" },
  { name: "Handcrafted mufflers", description: "Handmade mufflers from the BSGSS self-help group product collection, supporting practical skills and women-led enterprise.", image: "/images/bsgss/shg-products/muffler.png" },
];

export default function ShgProductsPage() { return <><PageHeader title="SHG products" lead="Handmade products created through women’s self-help groups supported by BSGSS." crumbs={[{ name: "Activities", path: "/activities" }, { name: "SHG products", path: "/activities/shg-products" }]} /><main className="py-16 sm:py-24"><div className="mx-auto max-w-6xl px-5 md:px-8"><section className="grid gap-8 rounded-2xl bg-brand-50 p-7 sm:p-10 md:grid-cols-[auto_1fr]"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-white text-brand-700 shadow-sm"><HandHeart className="h-7 w-7" /></div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-brand-700">Women-led enterprise</p><h2 className="mt-3 font-display text-3xl font-bold text-ink">Craft that supports livelihoods.</h2><p className="mt-4 max-w-3xl leading-relaxed text-ink-muted">BSGSS describes its SHG products as handmade items crafted by women&apos;s Self-Help Groups. The collection supports rural livelihoods, skill development and economic empowerment in Uttar Pradesh and Delhi.</p></div></section><section className="mt-14"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-brand-700">Current collection</p><h2 className="mt-3 font-display text-3xl font-bold text-ink">Made with care, connected to community.</h2></div><ShoppingBag className="h-8 w-8 text-brand-700" /></div><div className="mt-8 grid gap-6 md:grid-cols-2">{products.map((product) => <article key={product.name} className="overflow-hidden rounded-2xl border border-line bg-white shadow-sm"><div className="aspect-[5/3] bg-sand-50 p-6">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={product.image} alt={product.name} className="h-full w-full object-contain" /></div><div className="p-7"><h3 className="font-display text-2xl font-bold text-ink">{product.name}</h3><p className="mt-3 leading-relaxed text-ink-muted">{product.description}</p><a href={`mailto:bsgssindia@yahoo.co.in?subject=${encodeURIComponent(`SHG product enquiry — ${product.name}`)}`} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-700 hover:underline"><Mail className="h-4 w-4" /> Enquire with BSGSS</a></div></article>)}</div></section></div></main></> }
