import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, FileCheck2, Handshake, Route } from "lucide-react";
import { site } from "@/config/site";

export const metadata: Metadata = { title: "About BSGSS", description: site.description };

export default function AboutPage() {
  const cards = [{ title: "Our story", text: "Discover the journey from a village-rooted idea to practical community development.", href: "/about/our-story", icon: Route }, { title: "Legal status", text: "Access registrations, certificates and public compliance documents.", href: "/about/legal-status", icon: FileCheck2 }, { title: "Our partners", text: "Recognising CSR and government partners in social development through the years.", href: "/about/partners", icon: Handshake }, { title: "Our work", text: "Explore the programmes that connect education, health, skills and women’s empowerment.", href: "/our-work", icon: BookOpen }];
  return <><section className="bg-sand-50 py-16 sm:py-24"><div className="mx-auto max-w-4xl px-5 md:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-700">About BSGSS</p><h1 className="mt-3 font-display text-4xl font-bold text-ink">Building self-reliant communities since 1994.</h1><div className="mt-9 space-y-5 text-base leading-relaxed text-ink-muted"><p>Bisnouli Sarvodaya Gramodyog Sewa Sansthan (BSGSS) is a registered voluntary organisation founded in Bisnouli village, Dadri Tehsil, Uttar Pradesh. It works to foster sustainable socio-economic development through education, healthcare, vocational training and women’s empowerment.</p><p>BSGSS serves communities across Uttar Pradesh, Delhi, Punjab and Haryana with professionals, local partners and volunteers. Its work grew from a vision to promote village and cottage industries and strengthen self-reliance among underprivileged groups.</p><p>Guided by Shri Vijay Kumar Jha (Ex-IPS) and Smt. Nandita Bakshi (Ex-IRS), BSGSS focuses on practical, sustainable and community-driven solutions—enabling access to quality healthcare, education, skills, micro-finance and economic independence.</p></div></div></section><section className="py-16 sm:py-20"><div className="mx-auto max-w-6xl px-5 md:px-8"><h2 className="font-display text-3xl font-bold">Explore BSGSS</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{cards.map(({ title, text, href, icon: Icon }) => <Link key={href} href={href} className="group rounded-xl border border-line bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lift"><Icon className="h-6 w-6 text-brand-700" /><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-muted">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-brand-700">Explore <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section></>;
}
