import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Image as ImageIcon, ShoppingBag } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";

export const metadata: Metadata = { title: "Activities", description: "BSGSS activities and community programmes in action." };
const activities = [
  ["Community programmes", "gallery-community/192-whatsapp-image-2025-10-09-at-15-55-32-dd874b0a.jpg"], ["Healthcare camps", "healthcare-camps/150-camp3.jpeg"], ["Vocational training", "gallery-training/186-tal2.jpeg"], ["Education initiatives", "education/153-class4.jpeg"], ["Youth activities", "gallery-jac/161-jac3.jpg"], ["Events and outreach", "gallery-events/355-1-1.jpg"],
] as const;
export default function ActivitiesPage() { return <><PageHeader title="Activities" lead="A view into BSGSS programmes, training, community outreach and women-led enterprise." crumbs={[{ name: "Activities", path: "/activities" }]} /><main className="py-16 sm:py-24"><div className="mx-auto max-w-6xl px-5 md:px-8"><div className="grid gap-5 md:grid-cols-2"><Link href="/activities/gallery" className="group rounded-2xl border border-line bg-brand-50 p-7 transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md"><ImageIcon className="h-7 w-7 text-brand-700" /><h2 className="mt-5 font-display text-2xl font-bold text-ink">Activity gallery</h2><p className="mt-3 leading-relaxed text-ink-muted">Browse programme moments from community outreach, healthcare, skills training, education and events.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-700">View the gallery <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link><Link href="/activities/shg-products" className="group rounded-2xl border border-line bg-white p-7 transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md"><ShoppingBag className="h-7 w-7 text-brand-700" /><h2 className="mt-5 font-display text-2xl font-bold text-ink">SHG products</h2><p className="mt-3 leading-relaxed text-ink-muted">Discover handmade products created through women&apos;s self-help groups and the livelihood opportunities behind them.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-700">Explore products <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link></div><section className="mt-16"><p className="text-sm font-bold uppercase tracking-[.18em] text-brand-700">Programme moments</p><h2 className="mt-3 font-display text-3xl font-bold text-ink">Community work, in action.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{activities.map(([title, image]) => <figure key={image} className="group overflow-hidden rounded-xl border border-line bg-brand-100"><div className="aspect-[4/3] overflow-hidden">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={`/images/bsgss/${image}`} alt={title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><figcaption className="bg-white px-5 py-4 font-semibold text-ink">{title}</figcaption></figure>)}</div></section></div></main></> }
